const wheels = [
    {
        name: "Electric Wheelchair Wheel",
        price: 54.01,
        inStock: true,
        brand: "The Wheel Store",
        img: "",
        type: "Vehicles"
    },
    {
        name: "Western Style Wagon Wheel",
        price: 44.99,
        inStock: true,
        brand: "The Wheel Store",
        img: "",
        type: "Vehicles",
    },
    {
        name: "Toyota Wheel Rims",
        price: 125,
        inStock: true,
        brand: "The Wheel Store",
        img: "",
        type: "Vehicles",
    },
    {
        name: "Front Bicycle Wheels",
        price: 68.47,
        inStock: true,
        brand: "The Wheel Store",
        img: "",
        type: "Vehicles",
    },
    {
        name: "Auto Racing Steering Wheel",
        price: 24.91,
        inStock: true,
        brand: "The Wheel Store",
        img: "",
        type: "Vehicles",
    },
    {
        name: "Wheel Cog",
        price: 49.35,
        inStock: true,
        brand: "The Wheel Store",
        img: "",
        type: "Gears",
    },
    {
        name: "Wheel of Names",
        price: 0.00,
        inStock: true,
        brand: "The Wheel Store",
        img: "",
        type: "Extra",
    },
    {
        name: "Western Style Wagon Wheel",
        price: 44.99,
        inStock: true,
        brand: "The Wheel Store",
        img: "",
        type: "Wheel",
    },
    {
        name: "Western Style Wagon Wheel",
        price: 44.99,
        inStock: true,
        brand: "The Wheel Store",
        img: "",
        type: "Wheel",
    },
]